
version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: telegram_messages
      - name: image_detections

models:
  - name: stg_telegram_messages
    description: "Staging model for raw Telegram messages"
    columns:
      - name: message_id
        description: "Unique identifier for each message"
        tests:
          - not_null
          - unique

      - name: channel
        description: "Telegram channel name"
        tests:
          - not_null

      - name: date
        description: "Timestamp of message"
        tests:
          - not_null

  - name: stg_image_detections
    description: "Staging model for YOLOv8 image detection results"
