version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: telegram_messages

models:
  - name: stg_telegram_messages
    description: "Cleaned and structured telegram messages"
    columns:
      - name: message_id
        tests:
          - not_null
          - unique
      - name: message_date
        tests:
          - not_null
